# Generated by Django 2.1.3 on 2018-11-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Марка', max_length=200)),
                ('info', models.TextField(default='Текст объявления')),
                ('year', models.IntegerField(default=2012)),
                ('motor', models.CharField(default='2.8 Бензин', max_length=200)),
                ('price', models.DecimalField(decimal_places=1, default=2000000, max_digits=5)),
                ('color', models.CharField(default='Черный', max_length=200)),
                ('mileage', models.IntegerField(default=0)),
                ('drive', models.IntegerField(default=0)),
                ('wheel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Модель', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
