# Generated by Django 2.1.3 on 2018-11-25 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 17, 32, 8, 928651)),
        ),
    ]
