# Generated by Django 2.1.3 on 2018-11-25 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 17, 35, 34, 379047)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 17, 35, 34, 380046)),
        ),
    ]
