# Generated by Django 2.1.3 on 2018-11-25 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20181125_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picrure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 22, 50, 19, 7605)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 22, 50, 19, 8607)),
        ),
        migrations.AddField(
            model_name='picrure',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Car'),
        ),
    ]
