# Generated by Django 2.1.3 on 2018-11-25 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20181125_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picrure',
            new_name='Picture',
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 22, 52, 27, 719642)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 22, 52, 27, 719642)),
        ),
    ]
