# Generated by Django 2.1.3 on 2018-12-17 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20181125_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 13, 6, 40, 962116)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 13, 6, 40, 962116)),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
