# Generated by Django 2.1.3 on 2018-12-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
