# Generated by Django 2.1.3 on 2018-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
