# Generated by Django 2.1.3 on 2018-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_picture_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Город', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(default='Номер', max_length=12),
        ),
    ]
